name: 'Navy'
author: 'Clock Limited'
description: 'Communicate with a Navy Admiral and issue commands'
inputs:
  admiralHost:
    description: 'The address of the Navy Admiral host'
    required: true
  appId:
    description: 'The app ID you want to target'
    required: true
  order:
    description: 'The order the Admiral should execute'
    required: true
  version:
    description: 'The version you wish to provide'
    required: true
  environment:
    description: 'The environment you want to target, staging/production'
    required: true

outputs:
  success:
    description: 'If the order completed successfully or not'
runs:
  using: 'node16'
  main: './dist/index.js'
